media:
  - name: images
    label: Blog Images
    input: src/content/posts
    output: ./
    extensions: [png, jpg]
content:
  - name: about
    label: About
    type: file
    path: src/content/spec/about.md
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{short}.md"
    view:
      fields: [title, short, order, date]
      primary: short
      sort: [order, title]
      default:
        sort: order
        order: asc
    fields:
        - {name: title, label: Title, type: string, required: true}
        - {name: short, label: Short Title, type: string}
        - name: published
          label: Published
          type: date
          options:
            format: yyyy-MM-dd
        - {name: description, label: Description, type: string}
        - name: category
          label: Category
          type: select
          options:
            values: [Manga, Anime, Literature, Movie, Drama]
        - {name: draft, type: boolean, default: false, label: Draft?}
        - name: body
          label: Content
          type: code
          options:
             language: markdown