media:
  - name: images
    label: Logos
    input: src/assets/images
    output: media
  - name: Files
    label: Blog Images
    input: src/content/posts
    output: media
    extensions: [png, jpg]
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{primary}.md"
    view:
      fields: [title, order]
      primary: title
      sort: [order, title]
      default:
        sort: order
        order: asc
    fields:
        - {name: title, label: Title, type: string, required: true}
        - name: published
          label: Published
          type: date
          options:
            format: yyyy-mm-dd
        - {name: description, label: Description, type: string}
        - {name: tags, label: Tags, type: string}
        - name: category
          label: Category
          type: select
          options:
            values: [Manga, Anime, Literature, Movie, Shows]
        - {name: draft, type: boolean, default: false, label: Draft?}
        - {name: cover, type: image, label: Cover Image}
        - {name: body, label: Content, type: rich-text}