media:
  - name: images
    label: Blog Images
    input: src/content/posts
    output: src/content/posts
    extensions: [png, jpg]
content:
  - name: about
    label: About
    type: file
    path: src/content/spec/about.md
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    filename: "{primary}.md"
    view:
      fields: [title, order, date]
      primary: title
      sort: [order, title]
      default:
        sort: order
        order: asc
    fields:
        - {name: title, label: Title, type: string, required: true}
        - name: published
          label: Published
          type: date
          options:
            format: yyyy-MM-dd
        - {name: description, label: Description, type: string}
        - name: category
          label: Category
          type: select
          options:
            values: [Manga, Anime, Literature, Movie, Shows]
        - name: tags
          label: Tags
          type: code
          options:
            language: markdown
        - {name: draft, type: boolean, default: false, label: Draft?}
        - name: image
          type: image
          label: Cover Image
          options:
            path: posts
            output: ./
        - name: body
          label: Content
          type: rich-text