media:
  - name: images
    label: Blog Images
    input: src/content/posts
    output: ./
    extensions: [png, jpg]
content:
  - name: about
    label: About
    type: file
    path: src/content/spec/about.md
  - name: contact
    label: Contact
    type: file
    path: src/content/spec/contact.md
  - name: posts
    label: Posts
    type: collection
    path: src/content/posts
    extentions: [md]
    filename: "{primary}.md"
    view:
      fields: [title, short, order, date]
      primary: short
      sort: [order, title]
      default:
        sort: order
        order: asc
    fields:
        - {name: title, label: Title, type: string, required: true}
        - {name: short, label: Short Title, type: string}
        - name: published
          label: Published
          type: date
          options:
            format: yyyy-MM-dd
        - name: pubDate
          label: pubDate
          type: date
          options:
            format: yyyy-MM-dd  
        - {name: description, label: Description, type: string}
        - name: category
          label: Category
          type: select
          options:
            values: [Yuri, Yaoi, Trans, LGTBQIA+]
        - name: tags
          label: Tags
          type: select
          options:
            multiple: true
            values:
            - value: [anime]
              label: Anime
            - value: [drama]
              label: Drama
            - value: [documentary]
              label: Documentary
            - value: [game]
              label: Game
            - value: [literature]
              label: Literature
            - value: [manga]
              label: Manga
            - value: [movie]
              label: Movie
        - {name: draft, type: boolean, default: true, label: Draft}
        - name: body
          label: Content
          type: code
          options:
             language: markdown
             placeholder: "tags: []"